hengyoush/kyanos

.gitmodules
agent/analysis/stat.go
agent/conn/kern_event_handler.go
bpf/types.go

**Description:** Clean kern event stream when connection parser make progress
**Related Issues:** [List the issue numbers related to this PR]
**TODO**
**Checklist:**
**Screenshots:** [Provide relevant screenshots or GIF animations]

[Improvement] Clean kern event stream when connection parser make progress

---

agent/agent.go

In centos 3.10, start kyanos encounter error:

[Fix] log warn when remove mem lock failed

---

agent/agent.go
agent/agent_utils_test.go
agent/analysis/analysis.go
agent/analysis/stat.go
agent/common/stopper.go
agent/compatible/type.go
agent/conn/conntrack.go
agent/conn/kern_event_handler.go
agent/conn/processor.go
agent/protocol/common.go
agent/protocol/http.go
agent/protocol/mysql/handler.go
agent/protocol/mysql/mysql.go
agent/protocol/mysql/utils.go
agent/protocol/redis..go
agent/render/render.go
cmd/common.go
cmd/root.go
common/constant.go
common/log.go
common/type.go
common/utils.go
monitor/monitor.go

Add log level options to cmd:
```
--default-log-level int32           --default-log-level 4 # specify default log level, from 1(fatal level) to 5(debug level) (default 3)
--agent-log-level int32             --agent-log-level 4 # specify agent module log level individually
--bpf-event-log-level int32         --bpf-event-log-level 4 # specify bpf event log level individually
--conntrack-log-level int32         --conntrack-log-level 4 # specify conntrack module log level individually
--protocol-log-level int32          --protocol-log-level 4 # specify protocol module log level individually
```

[Improvement] Support setting different log levels for different modules.

---

agent/conn/conntrack.go

when Connection4 Onclose() be called, donot delete conn_info_map entry, because it may be other connection with same tgid but different ipport.

fix(conntrack): fix Connection4 OnClose func bug

---

agent/analysis/analysis.go
agent/analysis/classfier.go
agent/analysis/common/classfier.go
agent/analysis/common/types.go
agent/analysis/types.go
agent/render/stat/stat.go
cmd/overview.go
cmd/stat.go

feat. add overview subcommand

---

bpf/pktlatency.h

I couldn't compile the latest code without adding this.
Otherwise I got the error:
incompatible integer to pointer conversion assigning to 'struct socket *' from '__u64' (aka 'unsigned long long')

Add pragma to ignore int conversion warning in pktlatency.h

---

agent/agent.go
common/term.go

feat: add terminal color check

---

agent/agent.go

Add system info logging for crash reports
- Implemented a function to log system information when a crash occurs.
- The function collects OS, architecture, CPU count, Go version, kernel version, and Linux distribution details.
- Added formatted crash report output including error messages and system information.
- Included instructions for reporting issues on GitHub.
---
like this :
```bash
===================================
Kyanos Crash Report
=========Error Message=============
Error: !23
============OS Info================
OS: linux
Arch: amd64
NumCPU: 2
GoVersion: go1.23.3
Kernel Version: 5.15.0-72-generic
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/" …
```

feat: Print osinfo when start failed

---

COMPILATION.md
COMPILATION_CN.md
docs/cn/how-to-build.md
docs/how-to-build.md

Previous URL is a GitHub website, not raw content.
Correct URL:

docs: wrong url to download the init script

---

agent/conn/kern_event_handler.go

- Added missing mutex locks in discardSslEventsIfNeeded and discardEventsIfNeeded methods to ensure thread safety.
- Improved the logic for discarding SSL and kernel events by sequence.

fix: add rw lock to prevent concurrent map read write

---

.github/workflows/build_verification.yml
.github/workflows/check.yml
Makefile
bpf/loader/loader.go
init_env.sh

feat: introduce a new workflow to verify build script on multi platforms 

---

agent/agent.go
agent/common/options.go
agent/conn/processor.go
agent/render/watch/watch_render.go
cmd/root.go

Introduce a new option `conntrack-close-wait-time-mills` which control how long time before a `Connection4` turn into `closed` state. If too long, new connection with same tgidfd 's data may come into old connection  event stream or syscall data buffer, cause negative time. Set it  to a relatively small value  will prevent  this situation. (change 1s to 100ms(default))

fix(stat): elapsed time is negative

---

Makefile

- Introduced new Makefile targets for debugging: `dlv`, `kyanos-debug`, and `remote-debug`.
- The `dlv` target sets executable permissions and starts the debugger in headless mode.
- The `kyanos-debug` target builds the project with specific flags for debugging.
- The `remote-debug` target depends on building BPF and the `kyanos-debug` target, streamlining the debugging process.

build: add debugging targets and improve Makefile structure

---

.github/workflows/test.yml
testdata/https-request/http_request.go
testdata/start_http_server.py
testdata/test_filter_by_comm.sh

test: introduce a script to test flag `--comm`

---

agent/analysis/common/json.go
agent/render/watch/option.go
agent/render/watch/watch_render.go
cmd/watch.go
docs/.vitepress/config.mts
docs/cn/json-output.md
docs/cn/watch.md
docs/json-output.md
docs/watch.md
package-lock.json

- Added `--json-output` flag to watch command for programmatic data processing
- Added `--json-output-file` flag to specify custom output file path
- Default JSON output path is set to `/tmp/kyanos_watch.json`
- Export request-response data in structured JSON format
- Each JSON record includes:
- Detailed timing information (start/end time, various duration metrics)
- Connection details (protocol, addresses, ports)
- Content information (request/response sizes and content)
- Event details (syscall and NIC events)
- Support both default and custom output paths
- Added JSON output format documentation in both English and Chinese
- Updated watch command documentation to include JSON output usage

feat: Add json-output params to watch command

---

agent/compatible/type.go
bpf/agent_arm64_bpfel.go
bpf/agent_x86_bpfel.go
bpf/agentlagacykernel310_arm64_bpfel.go
bpf/agentlagacykernel310_x86_bpfel.go
bpf/pktlatency.bpf.c

CLOSE #117 
use `tracepoint/skb/skb_copy_datagram_iovec` to replace `kprobe/skb_copy_datagram_iovec` or `kprobe/__skb_datagram_iter`

fix: use tracepoint instead of kprobe to trace skb_copy_datagram_iovec

---

.github/workflows/test.yml
agent/agent.go
agent/common/permission.go
go.mod
go.sum
testdata/run_cap_bpf_test.sh
testdata/test_add_cap_bpf.sh
testdata/test_not_add_cap_bpf.sh

RESOLVE #224 
Reference：https://sites.google.com/site/fullycapable/getting-started-with-go/other-linux-capability-go-packages

feat: check cap privileges instead of `Geteuid` during starting the agent

---

agent/protocol/mysql/handler.go
bpf/gotls.bpf.c

fix: fix mysql protcol parser array index out of range issue and gotls load failed issue

---

agent/agent.go
agent/common/options.go
cmd/common.go
cmd/root.go

add `syscall-perf-event-map-page-num`, `ssl-perf-event-map-page-num`, `conn-perf-event-map-page-num`, `kern-perf-event-map-page-num` command-line options to set pageNum of `SyscallDataEvents`, `SslDataEvents`, `ConnDataEvents` and `KernEvents`.
This will fix #245

user: add command-line  options to set perf event buffer size

---

.github/workflows/test.yml
agent/conn/conntrack.go
agent/conn/processor.go
agent/protocol/fakedata.go
agent/protocol/http.go
agent/protocol/http_test.go
bpf/data_common.h
testdata/test_truncated_data.sh

When we fail to read the http body, it might be due to the response being too large, causing syscall data to be missing when transferred to user space. 
Here, we attempt to find a boundary. If found, that's ideal and we return immediately. Otherwise, we try to locate a Fake Data Mark (FDM). When user space detects missing data from the kernel (possibly due to exceeding MAX_MSG_SIZE or situations like readv/writev where a buffer array is read/written at once), it supplements with fake data in user space.
At the beginning of this fake data, an FDM is set, which is a special string. Following the FDM, the length of the supplemental fake data (minus the length of the FDM) is written.

fix: handle big syscall data (truncated) properly

---

agent/compatible/type.go
bpf/agent_arm64_bpfel.go
bpf/agent_x86_bpfel.go
bpf/agentlagacykernel310_arm64_bpfel.go
bpf/agentlagacykernel310_x86_bpfel.go
bpf/loader/loader.go
bpf/pktlatency.bpf.c
testdata/test_ipv6.sh

Currently github action runner doesn't support ipv6, so only write an e2e test script but not added to test.yml workflow.

feat: support trace socket event for ipv6

---

agent/agent.go
agent/uprobe/manager.go

feat: check pid when attaching uprode.

---

cmd/root.go

fix: wrong param name
